version: "3"
services:
    frontend:
        container_name: tubetest-frontend
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/client
            - /usr/src/client/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true 
        stdin_open: true
    
