CREATE TABLE IF NOT EXISTS timestamps(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp text NOT NULL CHECK (timestamp <> '')
);


INSERT INTO timestamps (timestamp)
VALUES ('10:01:02');

INSERT INTO timestamps (timestamp)
VALUES ('04:02:23');

INSERT INTO timestamps (timestamp)
VALUES ('20:44:58');

-- Insert task data