version: "3"
services:
    postgres:
        image: "postgres"
        restart: always
        volumes:
              - ./pgdata:/var/lib/postgresql/data
              - ./db.sql:/docker-entrypoint-initdb.d/db.sql
        environment:
                   POSTGRES_USER: postgres
                   POSTGRES_PASSWORD: root
                   POSTGRES_DB: postgres
                   PGDATA: /tmp
        ports:
            - "5432:5432"
    backend:
        container_name: tubetest-backend
        #entrypoint: ["/bin/bash", "./entrypoint.sh"]
        restart: always
        build: .
        ports:
            - "4000:4000"
        depends_on:
                - postgres
        volumes:
            - .:/usr/src/app
    
